### PR TITLE
Initial commit of an implementation for #132

### PR DESCRIPTION
**Pull request by Riduidel**
Please review this PR, which contains a working implementation of a writer using the C4-PlantUML sprite library.

### CODE REVIEW

**Comment by Riduidel** [comment]
Also notice there is not yet support for boundaries, which will require a refactoring of the `PlantUMLWriter`.

**Comment by Riduidel** [comment]
This pull request has bugs. Typically, for layout links, the parameters list is not the same.
I'll have to rework on that later. Do you wish I create another PR, or do you prefer I update this one ?

**Comment by simonbrowndotje** [comment]
I'm contemplating splitting the repo as follows:

1. structurizr-core and structurizr-client
2. Everything else

Although the core and client libraries need to be stable (because I'm supporting them as a part of the Structurizr service), it's very clear to me that I'm a bottleneck with merging PRs for all of the various extensions being built. Do you think this is a good idea? And would you be interested in being added as a contributor the second repo?

**Comment by Riduidel** [comment]
yeah, idea is very good. And I would like to be a contributor to that "structurizr-extensions" (or whatever name you choose) project.

**Pull request merged**
