### PR TITLE
fixed Container null issues with addComponent

### PR DESCRIPTION
**Pull request by KKorzuno**
Still many issues persist in id setup, but that requires a deeper understanding of the topic. I expect to have fixed the immediate issue that one gets null issue warnings when doing "addComponent" on a container.

### CODE REVIEW

**Comment by KKorzuno** [comment]
Be gentle, my first pull request ever...

**Comment by simonbrowndotje** [comment]
You seem to have deleted some code in `Model.addRelationship()`?

**Comment by KKorzuno** [comment]
I started checking this today actually. There are many places where null is returned  (like getXByName). Together with Nonnull on method entry makes it just confusing :(
This would require a rework to be really nonnull compliant (by operating on "" strings or having "hasComponentWithName")...

**Comment by simonbrowndotje** [comment]
> makes it just confusing

Agreed ... the `@Nonnull` annotations do very little. I'd personally like to remove them all.

**Comment by simonbrowndotje** [comment]
Closing as stale ... feel free to open a new PR if you still want to add those annotations.

**Pull request closed without merging**
