### PR TITLE
Added some functionality for dynamic diagrams

### PR DESCRIPTION
**Pull request by GuidoDechamps**
Simon,

I wanted to create some dynamic diagrams to complement my static ones. The existing code did not do exactly what i wanted. The things i wanted were:
-  i needed een regex class matcher, not just a suffix one.
-  I also wanted to add tags depending on which class rule i match.
- The TypeBasedComponentFinderStrategy established some strange relations between classes and interfaces that i did not want or understood. I wanted the relation ships between components to be calculated differently.

In order to be able to add all this functionality i added a package func under the componentfinder package. I introduced my own _FunctionalComponentFinder_ instead of using the existing _ComponentFinder_. The _FunctionalComponentFinder_ does not use the existing strategy setup but allows me to easily create dynamic diagrams. For testing purposes i also added some dummy example code that i still had. A dummy paperboy example. This is just use for testing purposes of the componentfinder. I placed this code under _com.structurizr.testapp.paperboy_

With the three important classes that perform directly to the three mentioned points being:
- TagDecorator
- RegexClassNameMatcher
- FunctionalComponentFinder

The test FunctionalComponentFinderTest documents the different use cases and the difference in calculating dependencies.

Apart from this i wrote some additional helper classes that, in combination with the structurizr additions i made, enable me to create diagrams faster. An example of this here:
[HowIUseStructurizrNow.txt](https://github.com/structurizr/java/files/348172/HowIUseStructurizrNow.txt)

Feel free to use or discard all of the above..

Regards,
Guido

### CODE REVIEW

**Comment by simonbrowndotje** [comment]
Thanks Guido. Do you have any examples (e.g. diagrams) of the components and dependencies found by the existing component finders versus your FunctionalComponentFinder? I'm not sure whether you've found some issues or you're just trying to do something different from what I designed Structurizr to do. What would you consider to be "components" in the paperboy app?

Cheers
Simon

**Comment by GuidoDechamps** [comment]
The test [FunctionalComponentFinderTest](https://github.com/GuidoDechamps/java/blob/master/structurizr-core/test/unit/com/structurizr/componentfinder/func/FunctionalComponentFinderTest.java) creates components using my DirectDependencyScanner as well as the StructurizrDependenciesScanner. They each have their own validator that illustrates the difference. The DirectDependenciesValidator and the StructurizrDependenciesValidator. The structurizr version gives java interfaces a dependency on their implementation and on all the dependencies of the first implementation. I dont want the interfaces to have such dependencies. i want the implementations to have a dependency on their interface. A relation that i can then name IMPLEMENTS.

```java
/**
 * Copy off how dependencies are calculated in AbstractReflectionsComponentFinderStrategy,
 * modified a bit to use scan result
 * <p>
 * This algorithm gives Interfaces:
 * <ol>
 * <li>a dependency on their implementation</li>
 * <li>a dependency on all the dependencies of the first implementation</li>
 * </ol>
 * <p>
 * I don't understand why  :)
 */
enum StructurizrDependenciesScanner implements DependenciesScanner
```

**Comment by GuidoDechamps** [comment]
The image when generate in [paperboy structurizr 0.7.1](https://cloud.githubusercontent.com/assets/3738043/16614828/97d13216-4373-11e6-922b-c19ea467dd9a.png)
The image when generate in [paperboy structurizr 0.8.1](https://cloud.githubusercontent.com/assets/3738043/16614855/c41e138e-4373-11e6-8fe3-eeca2998c8e5.png)

In 0.7 there is a strange triangle of depenencies between the application service interface and its implementation. In version 0.8.1 it looks as i expect it would. Could be the result of solving issue PR29. 

The diagrams were generated with identical code. use native Structurizr only.

```java
 private static ComponentFinderStrategy createTypeBasedComponentFinderStrategy() {
        return new TypeBasedComponentFinderStrategy(
                new NameSuffixTypeMatcher("Repository", "A repository", ""),
                new NameSuffixTypeMatcher("Service", "A Service", ""),
                new NameSuffixTypeMatcher("Wallet", "Domain model", ""),
                new NameSuffixTypeMatcher("Paper", "Domain Model", ""),
                new NameSuffixTypeMatcher("Customer", "Domain model", ""),
                new NameSuffixTypeMatcher("Address", "Domain model", ""),
                new NameSuffixTypeMatcher("PaperBoy", "Domain model", ""));
    }
```

**Comment by simonbrowndotje** [comment]
Thanks Guido. It sounds like you're trying to use Structurizr to model a lower level of detail than it was designed to. In most cases, the concept of a "component" is the public interface and all of it's supporting implementation classes. This is why the existing component finder code will try to find the types implementing/referenced by the "component type". Perhaps a UML class diagram might be better for showing this level of detail?

**Comment by GuidoDechamps** [comment]
No not really, that is exactly what i want. And with the latest version it was rendered ok. My func impl allows me to modify my diagrams more easily.

**Pull request closed without merging**
